// <auto-generated />
using System;
using FaturaTakip.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaturaTakipAPI.Migrations
{
    [DbContext(typeof(FaturaTakipDbContext))]
    [Migration("20231005151132_SirketAdi")]
    partial class SirketAdi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FaturaTakip.Models.Faturalar", b =>
                {
                    b.Property<int>("FaturaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaturaID"), 1L, 1);

                    b.Property<decimal?>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("FaturaNo")
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KDVOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Miktar")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriID")
                        .HasColumnType("int");

                    b.Property<decimal?>("OdenecekTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SiparisNo")
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SirketID")
                        .HasColumnType("int");

                    b.Property<string>("Urun")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar(100)");

                    b.HasKey("FaturaID");

                    b.HasIndex("MusteriID");

                    b.HasIndex("SirketID");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("FaturaTakip.Models.Musteriler", b =>
                {
                    b.Property<int>("MusteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar(100)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("Eposta")
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<int?>("SirketID")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("TelefonNo")
                        .HasMaxLength(15)
                        .HasColumnType("Varchar(15)");

                    b.HasKey("MusteriID");

                    b.HasIndex("SirketID");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("FaturaTakip.Models.Sirketler", b =>
                {
                    b.Property<int>("SirketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SirketID"), 1L, 1);

                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar(100)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("Varchar(255)");

                    b.Property<string>("SirketAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("TelefonNo")
                        .HasMaxLength(15)
                        .HasColumnType("Varchar(15)");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("VergiKimlikNo")
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("WebAdresi")
                        .HasMaxLength(200)
                        .HasColumnType("Varchar(200)");

                    b.HasKey("SirketID");

                    b.ToTable("Sirketler");
                });

            modelBuilder.Entity("FaturaTakip.Models.Faturalar", b =>
                {
                    b.HasOne("FaturaTakip.Models.Musteriler", "Musteri")
                        .WithMany("Fatura")
                        .HasForeignKey("MusteriID");

                    b.HasOne("FaturaTakip.Models.Sirketler", "Sirket")
                        .WithMany("Fatura")
                        .HasForeignKey("SirketID");

                    b.Navigation("Musteri");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("FaturaTakip.Models.Musteriler", b =>
                {
                    b.HasOne("FaturaTakip.Models.Sirketler", "Sirket")
                        .WithMany("Musteri")
                        .HasForeignKey("SirketID");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("FaturaTakip.Models.Musteriler", b =>
                {
                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("FaturaTakip.Models.Sirketler", b =>
                {
                    b.Navigation("Fatura");

                    b.Navigation("Musteri");
                });
#pragma warning restore 612, 618
        }
    }
}
